    <div id="sideBar">
        <table style="width:100%">
            <tr><td class="recent"><a href="#">H0000001</a><div id="sidebarRecent">Allred Equipment, Inc.</div></td></tr>
            <tr><td class="recent"><a href="#">H0000001</a><div id="sidebarRecent">Allred Equipment, Inc.</div></td></tr>
            <tr><td class="recent"><a href="#">H0000002</a><div id="sidebarRecent">Allred Equipment, Inc.</div></td></tr>
            <tr><td class="recent"><a href="#">H0000003</a><div id="sidebarRecent">Allred Equipment, Inc.</div></td></tr>
        </table>  
  
    </div>
